export const articles = [
  {
    "id": 122,
    "slug": "ijirare-2",
    "category_id": 1,
    "author_id": 1,
    "episode_list": "4",
    "current_episode": 2,
    "poster": "https://i.imgur.com/yc08l9j.png",
    "name": "Ijirare: Fukushuu Saimin 2",
    "name_second": "Bullied: Revenge Hypnosis",
    "name_japanese": "イジラレ ～復讐催○～",
    "synopsis": "Бүх эрчүүд түүний хувьд зүгээр л нэг эвдэртэл нь тэгж хаядаг тоглоом. Энэ нүдний шилтэй тарган банди ч бас ялгаагүй... хувцас солих өрөөнд дотуур хувцсыг нь үнэрлэж байхыг хараад өөр нэг тоглоомтой болов. Эсвэл тэгж бодов уу...",
    "status": 0,
    "aired_at": "2021-02-05",
    "duration": "16",
    "embed_watch": null,
    "studio": "T-Rex",
    "translator": "Renshou",
    "views": 4143,
    "created_at": "2022-05-04T14:57:31.000000Z",
    "updated_at": "2022-05-04T14:57:31.000000Z",
    "sub_mn": "Fukkatsu.Ijirare-Fukushuu.Saimin-02-mn.vtt",
    "sub_eng": null,
    "stream_720": "Ijirare-Fukushuu.Saimin-02-720.mp4",
    "posted_at": null
    },
    {
    "id": 121,
    "slug": "hanako-1",
    "category_id": 1,
    "author_id": 1,
    "episode_list": "4",
    "current_episode": 1,
    "poster": "https://i.imgur.com/kPl3uSA.png",
    "name": "Toilet no Hanako-san vs Kukkyou Taimashi 1",
    "name_second": "Toilet no Hanako-san vs Kukkyou Taimashi",
    "name_japanese": "トイレの花子さんVS屈強退魔師",
    "synopsis": "Мартагдаж хаягдсан сургууль дотор тэнүүчлэх хорон сүнс Ханако-сан дээр нэгэн хувраг айлчилна.",
    "status": 0,
    "aired_at": "2021-02-26",
    "duration": "16",
    "embed_watch": null,
    "studio": "Suzuki Mirano",
    "translator": "Hanzo",
    "views": 6358,
    "created_at": "2022-04-28T15:55:24.000000Z",
    "updated_at": "2022-04-28T15:55:24.000000Z",
    "sub_mn": "Fukkatsu.Toire.no.Hanako-san-01-mbsub.vtt",
    "sub_eng": null,
    "stream_720": "Toire.no.Hanako-san.vs.Kukkyou.Taimashi-01-480.mp4",
    "posted_at": null
    },
    {
    "id": 120,
    "slug": "inkou-1",
    "category_id": 1,
    "author_id": 1,
    "episode_list": "2",
    "current_episode": 1,
    "poster": "https://i.imgur.com/gVanfty.png",
    "name": "Inkou Kyoushi no Saimin Seikatsu Shidouroku 1",
    "name_second": "Inkou Kyoushi no Saimin Seikatsu Shidouroku",
    "name_japanese": "Inkou Kyoushi no Saimin Seikatsu Shidouroku",
    "synopsis": "Хүссэн хүнээ хүслээрээ удирдаж чаддаг дэвтэр олоод сайтар гэгч нь ашиглахаар төлөвлөв. Сургуулийнхаа хамгийн хөөрхөн охиныг олцгооё.",
    "status": 0,
    "aired_at": "2022-04-01",
    "duration": "16",
    "embed_watch": null,
    "studio": "T-Rex",
    "translator": "nanda",
    "views": 6113,
    "created_at": "2022-04-28T15:50:24.000000Z",
    "updated_at": "2022-04-28T15:50:24.000000Z",
    "sub_mn": "Fukkatsu.Inkou.Kyoushi.no.Saimin.Seikatsu.Shidouroku-01-mnsub.vtt",
    "sub_eng": null,
    "stream_720": "Inkou.Kyoushi.no.Saimin.Seikatsu.Shidouroku-01-720.mp4",
    "posted_at": null
    },
    {
    "id": 119,
    "slug": "fella-pure-1",
    "category_id": 1,
    "author_id": 1,
    "episode_list": "1",
    "current_episode": 1,
    "poster": "https://i.imgur.com/NZhXIyk.jpg",
    "name": "Fella Pure: Mitarashi-san Chi no Jijou The Animation",
    "name_second": "Fela Pure: Mitarashi-san Chi no Jijou - The Animation",
    "name_japanese": "フェラピュア ~御手洗さん家の事情~ THE ANIMATION",
    "synopsis": "Бүгд сурагчдын зөвлөлийн даргыг төгс охин гэж хардаг ч түүний жинхэнэ төрхийг зөвхөн дүү нь л мэднэ. Тэдний эцэг, эх байнга аялж байдаг учраас тэд өөрсдийнхөө хүслийг янз янзаар хангана.",
    "status": 0,
    "aired_at": "2014-03-28",
    "duration": "29",
    "embed_watch": null,
    "studio": "Office Takeout",
    "translator": "Aki",
    "views": 10244,
    "created_at": "2022-04-16T17:24:58.000000Z",
    "updated_at": "2022-04-16T17:24:58.000000Z",
    "sub_mn": "Fela.Pure-Mitarashi-san.Chi.no.Jijou-01-mn.vtt",
    "sub_eng": null,
    "stream_720": "Fela.Pure-Mitarashi-san.Chi.no.Jijou-01-540.mp4",
    "posted_at": null
    },
  ]